config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :prospects

  root 'application#home'
  get '/home' => 'application#home'
  
  devise_for :users, :skip => [:sessions]

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/auth/:provider/callback' => 'authentications#create_auth', via: [:get, :post]

  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get '*path' => 'application#index', as: 'dashboard'

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  belongs_to :user
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @prospects = Prospect.all
    respond_with(@prospects)
  end

  def show
    respond_with(@prospect)
  end

  def new
    @prospect = Prospect.new
    respond_with(@prospect)
  end

  def edit
  end

  def create
    @prospect = Prospect.new(prospect_params)
    @prospect.save
    respond_with(@prospect)
  end

  def update
    @prospect.update(prospect_params)
    respond_with(@prospect)
  end

  def destroy
    @prospect.destroy
    respond_with(@prospect)
  end

  private
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    def prospect_params
      params.require(:prospect).permit(:name, :first_name, :industry, :image_url, :linkedin_profile_url, :job_description, :location, :email, :user_id, :a)
    end
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/prospects/_form.html.erb
<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% @prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :linkedin_profile_url %><br>
    <%= f.text_field :linkedin_profile_url %>
  </div>
  <div class="field">
    <%= f.label :job_description %><br>
    <%= f.text_field :job_description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :a %><br>
    <%= f.text_field :a %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing prospect</h1>

<%= render 'form' %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<h1>Listing prospects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Industry</th>
      <th>Image url</th>
      <th>Linkedin profile url</th>
      <th>Job description</th>
      <th>Location</th>
      <th>Email</th>
      <th>User</th>
      <th>A</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.name %></td>
        <td><%= prospect.first_name %></td>
        <td><%= prospect.industry %></td>
        <td><%= prospect.image_url %></td>
        <td><%= prospect.linkedin_profile_url %></td>
        <td><%= prospect.job_description %></td>
        <td><%= prospect.location %></td>
        <td><%= prospect.email %></td>
        <td><%= prospect.user_id %></td>
        <td><%= prospect.a %></td>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/new.html.erb
<h1>New prospect</h1>

<%= render 'form' %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prospect.name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @prospect.first_name %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @prospect.industry %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @prospect.image_url %>
</p>

<p>
  <strong>Linkedin profile url:</strong>
  <%= @prospect.linkedin_profile_url %>
</p>

<p>
  <strong>Job description:</strong>
  <%= @prospect.job_description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @prospect.location %>
</p>

<p>
  <strong>Email:</strong>
  <%= @prospect.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @prospect.user_id %>
</p>

<p>
  <strong>A:</strong>
  <%= @prospect.a %>
</p>

<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>